title: BatLit - The Bat Literature Project
description: An open-access literature archive supporting bat taxonomy, ecology, and conservation.
email: batlitproject@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://batlit.org" # the base hostname & protocol for your site
markdown: kramdown
theme: minima
header_pages:
  - page: about.md
    title: About
  - page: search.md
    title: Search BatLit
  - url: https://zenodo.org/communities/batlit
    title: Zenodo Collection
  - url: https://batlit.org/datapaper
    title: Data Paper  
  - page: join.md
    title: Get Involved
  - page: contribute.md
    title: Upload Literature
